const mongoose=require("mongoose")

const snippetSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

  originalCode: { type: String, required: true },
  summary: { type: String }, // Generated by Gemini
  editedSummary: { type: String }, 

  dayNumber: { type: Number }, 
  hashtags: [String], 

  isPosted: { type: Boolean, default: false },
  platformsPostedTo: [String], 

  createdAt: { type: Date, default: Date.now }
});

module.exports=mongoose.model("Snippet", snippetSchema);
